services:
  - type: web
    name: tomato-disease-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn fastapi_server_h5:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TF_USE_LEGACY_KERAS
        value: "1"
      - key: PYTHON_VERSION
        value: "3.10.0"
    plan: free
